name: BlockSurvival
version: 1.0.0
author: BAEGMON
description: BlockSurvival plugin for Spigot/Bukkit
main: baegmon.blocksurvival.BlockPlugin
website: https://github.com/baegmon
commands:
  blocksurvival:
    description: Main command used to create arenas and start games
    usage: /blocksurvival help
    aliases: [bs]